### PR TITLE
Update postgres 

### PR DESCRIPTION
**Pull request by tgbdc7**
Update postgres version to 16. Refactor readme. 

Before build docker image rebuild database with command: `docker compose down -v`  or  `make drop`. This will delete all data from the database.

### CODE REVIEW

**Comment by bartmkraus** [comment]
Based on the recommendations provided in this article ([this article](https://nandovillalba.medium.com/docker-compose-tricks-and-best-practices-5e7e43eba8eb)) and considering general best practices, I believe it would be more advisable to utilize the postgres:16.1-alpine3.18 image instead of postgres:16.

**Comment by szmktk** [comment]
@bartmkraus Good article but 
> and yes you should always use [alpine](https://thenewstack.io/alpine-linux-heart-docker/) whenever possible!

Is not *always* true.
Always be aware of anyone using *always* in a domain in which every answer begins with *it depends* 😉 

Just wanted to bring this up as alpine [may not be the best fit for Python apps.](https://pythonspeed.com/articles/alpine-docker-python/). IMO it's OK to use it for PostgreSQL container.

**Comment by bartmkraus** [comment]
@szmktk I guess that's why the author of the article used the word "whenever possible".

**Comment by szmktk** [comment]
@bartmkraus And I don't agree with him. It's possible to use `alpine` in any python app, but it does not make sense to do so (longer build times, complex dockerfiles)

**Comment by miniMax18** [comment]
Let's try with alpine on first- alpine mountains v^v^v, we will consult it before real deploy :)

**Review by szmktk — APPROVED** [review]

**Pull request merged**
